name: App CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - uses: kprasadpn/github-platform-workflows/.github/actions/codeql-init@main
        with:
          language: python
          build-mode: none

      - uses: kprasadpn/github-platform-workflows/.github/actions/ci-build@main
        with:
          app-name: vulnerable-python-demo
          python-version: "3.11"

      - uses: kprasadpn/github-platform-workflows/.github/actions/ci-unit-test@main
        with:
          python-version: "3.11"

      - uses: kprasadpn/github-platform-workflows/.github/actions/codeql-analyze@main
        with:
          language: python

  dependency-review:
    if: github.event_name == 'pull_request'
    uses: kprasadpn/github-platform-workflows/.github/workflows/dependency-review.yml@main
    with:
      fail-on-severity: high

  secret-scan:
    uses: kprasadpn/github-platform-workflows/.github/workflows/secret-scan.yml@main
