name: App CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: <your-github-username>/github-platform-workflows/.github/workflows/ci-build.yml@main
    with:
      app-name: vulnerable-python-demo
      python-version: "3.11"

  unit-test:
    uses: <your-github-username>/github-platform-workflows/.github/workflows/ci-unit-test.yml@main
    with:
      python-version: "3.11"

  ghas-analyze:
    uses: <your-github-username>/github-platform-workflows/.github/workflows/ghas-analyze.yml@main
    with:
      language: python
      build-mode: none

  dependency-review:
    if: github.event_name == 'pull_request'
    uses: <your-github-username>/github-platform-workflows/.github/workflows/dependency-review.yml@main
    with:
      fail-on-severity: high

  secret-scan:
    uses: <your-github-username>/github-platform-workflows/.github/workflows/secret-scan.yml@main
